language: node_js
node_js:
- '8'
script:
- npm run lint
- npm run test-coverage
- npm run codecov
deploy:
  provider: pages
  skip-cleanup: true
  gitub-token: $GITHUB_TOKEN
  target_branch: master
  keep-history: true
  on:
    branch: master
