language: node_js
node_js:
- '8'
script:
- npm run build
- npm run lint
- npm run test-coverage
- npm run codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  target-branch: gh-pages
  fqdn: opi.mooc.fi
  on:
    branch: master
